#! /bin/sh

# Mount ftp
curlftpfs ftp://dong:flux2959@dymaxionkim.iptime.org:3001/HDD1 /home/osboxes/Dymaxionkim

# X-screen Saver off
xset -dpms
xset s off
xset s noblank

# Start
xrdb -merge ~/.Xresources
exec i3
